### ISSUE TITLE
about testing with webpack and tape

### ISSUE THREAD

**Issue by bySabi** [Jbarget/ReadingMaterial#1]
Hi @Jbarget.
I see your post http://stackoverflow.com/questions/37928165/source-maps-not-working-with-webpack
It seen that you know how test webpack bundle output with `tape`.
I wanna run `tape` or `tape-watch` watching for changes on `bundle.test.js` produced by webpack on `--watch` mode. I don´t know it is possible.

can you share you `webpack.test.config.js` file?
any advice on?

**Comment by Jbarget** [comment]
hey @bySabi i have actuallly changed my set up since that question
I now use mocha and dont bundle my tests up with the tests being run on the uncompiled code

**Comment by Jbarget** [comment]
```
const webpack = require('webpack');

module.exports = {
  entry: [
    'webpack-dev-server/client?http://localhost:8080/',
    'webpack/hot/dev-server',
    './src/index.js'
  ],
  output: {
    filename: 'bundle.js',
    path: '/'
  },
  resolve: {
    extensions: ['', '.jsx', '.scss', '.js', '.json']
  },
  module: {
    preLoaders: [
      {test: /\.(js|jsx)$/, loader: 'eslint-loader', exclude: /node_modules/}
    ],
    loaders: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loaders: ['react-hot','babel']
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css?sourceMap', 'sass?sourceMap']
      }
    ]
  },
  eslint: {
    configFile: './.eslintrc'
  },
  externals: {
    'cheerio': 'window',
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
  },
  debug: true,
  devtool: 'source-map',
  devServer: { hot: true, historyApiFallback: true },
  plugins: [ new webpack.HotModuleReplacementPlugin() ],
  inline: true,
  progress: true,
  colors: true
};

```

**Comment by Jbarget** [comment]
so at the moment my tests have nothing to do with webpack

**Comment by bySabi** [comment]
Thanks anyway! 
Actually I have a working setup of  `karma` and  `webpack` with enable autowatch. This two packages make it really well. The failing part is `karma-tap` ... output is very poor ... Maintainer don´t update it cause he don´t use it anymore.
I have the incomer impression than `tape` lost his moment and developers move back to `jasmine`, `mocha` ... Any thoung on this ???

I start to test [prova](https://github.com/azer/prova) tape runner...

**Comment by Jbarget** [comment]
Im generally happy with `tape` but because most of the documentation and examples for react and webpack use jasmine or mocha I think thats why most people use it.

Would you be able to show me your webpack.config? Im interested to see how you got karma working because i saw there are a lot of plugins

**Comment by bySabi** [comment]
Sure!

This a [WIP](https://github.com/bySabi/react-scrollto/tree/WIP) branch of a wip module 'react-scrollto'. `package.json` is a little messy cause I´m testing different approach

Feel free to ask me.

**Comment by bySabi** [comment]
@Jbarget 
This project have two `specs` settings. One with `browserify`, `babelify` and `tape` and another with `karma`, `webpack` and `karma-tap`

First one works good but I miss 'watch for source changes', you can test it with: `npm run tape`

The second, with `karma`, autowatch function work really well but  `karma-tap` output is not enough and `reporters` (prettifyers) is not like `faucet` or `tap-spec`.  See your self `npm run testonly:jsdom`
